application: field-promotion
module: default
version: react1
runtime: go
api_version: go1

handlers:

- url: /img
  static_dir: dist/img

- url: /scripts
  static_dir: dist/scripts

- url: /styles
  static_dir: dist/styles

- url: /.*
  script: _go_app
  login: required

skip_files:
  - ^node_modules$
  - ^app$
  - ^app2$