application: field-promotion
version: 9
runtime: python27
threadsafe: true
api_version: 1

handlers:

- url: /game.*
  script: py.rest_handler.app
  login: required

- url: /stat.*
  script: py.rest_handler.app
  login: required

- url: /img
  static_dir: app/img

- url: (.*)/
  static_files: app\1/index.html
  upload: app
  login: required

- url: (.*)
  static_files: app\1
  upload: app
  login: required

builtins:
- remote_api: on